### ISSUE TITLE
error on new install on m1 air 

### ISSUE THREAD

**Issue by shedali** [jameslittle230/homebrew-stork-tap#1] opened 2022-02-13 13:52 UTC
`brew tap stork-search/homebrew-stork-tap`
`brew install stork`

homebrew 3.3.14

```bash
❯ brew install stork
Warning: Treating stork as a formula. For the cask, use homebrew/cask/stork
==> Downloading https://github.com/jameslittle230/stork/archive/v1.4.0.tar.gz
Already downloaded: /Users/franz/Library/Caches/Homebrew/downloads/4b63ec8c1af01cc83f166171503cd48930be85bcf3796891d80a96560b2fdb5c--stork-1.4.0.tar.gz
==> Installing stork from stork-search/stork-tap
==> cargo install
Last 15 lines from /Users/franz/Library/Logs/Homebrew/stork/01.cargo:
2022-02-13 13:38:28 +0000

cargo
install
--locked
--root
/opt/homebrew/Cellar/stork/1.4.0
--path
.

error: found a virtual manifest at `/private/tmp/stork-20220213-84392-wx42wi/stork-1.4.0/Cargo.toml` instead of a package manifest
objc[84585]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libamsupport.dylib (0x1fe523678) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105b0c2c8). One of the two will be used. Which one is undefined.
objc[84585]: Class AMSupportURLSession is implemented in both /usr/lib/libamsupport.dylib (0x1fe5236c8) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x105b0c318). One of the two will be used. Which one is undefined.
```

**Comment by jameslittle230** [comment] 2022-02-16 01:04
Oh no! I'll take a look and update here when I figure out what's wrong.

James

**Comment by jameslittle230** [comment] 2022-03-15 16:55
Sorry about the delay here!

This regression was caused by a new file structure in the main Stork project. The installation script wasn't pointing to the correct directory from which to start compilation. The fix was published via https://github.com/stork-search/homebrew-stork-tap/commit/e94bc7f78750d48db208dbe800faaadea1dd5033.

`brew install stork-search/stork-tap/stork` should work as expected. I'm going to close this issue, but please reopen it if it's not working for you!

-James

**Closed as completed by jameslittle230** 2022-03-15 16:55 UTC
